
    
api:
  user-service:
    token:
      verify: http://localhost:8061/oauth/check_token


config:
  security:
    securityEnabled: 1


#security:
 # oauth2:
  #  resource:
   #   token-info-uri: http://localhost:8051/oauth/check_token
    #client:
     # client-id: mobile
      #client-secret: pin
