eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${random.int}
    
api:
  user-service:
    token:
      verify: http://oauthserver/oauth/check_token


#security:
 # oauth2:
  #  resource:
   #   token-info-uri: http://localhost:8051/oauth/check_token
    #client:
     # client-id: mobile
      #client-secret: pin
