server:
  port: 8063
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  #instance:
   # instance-id: ${spring.application.name}-${random.int}
    #hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin4321
    driver-class-name: com.mysql.jdbc.Driver
    #initialization-mode: always
    jpa:
      hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      properties:
      show_sql: true
      format_sql: true
 
 logging:
    level:
      org:
        hibernate:
          type: trace

hystrix:
  timeout: 1000



api:
  user-service:
    token:
      verify: http://localhost:8061/oauth/check_token


#security:
 # oauth2:
  #  resource:
   #   token-info-uri: http://localhost:8051/oauth/check_token
    #client:
     # client-id: mobile
      #client-secret: pin
