server:
  port: 8062
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profileDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin4321
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #ddl-auto: create
  
#security:
 # oauth2:
  #  resource:
   #   token-info-uri: http://localhost:8051/oauth/check_token
    #client:
     # client-id: mobile
      #client-secret: pin


api:
  user-service:
    token:
      verify: http://localhost:8061/oauth/check_token?token=
