server:
  port: 8064
     
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicleDB?vehicleDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin4321
    driver-class-name: com.mysql.jdbc.Driver
    #initialization-mode: always
    jpa:
      hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
      properties:
      show_sql: true
      format_sql: true
 
  api:
  user-service:
    token:
      verify: http://localhost:8061/oauth/check_token

config:
  security:
    securityEnabled: 1
  
  logging:
    level:
      org:
        hibernate:
          type: trace


hystrix:
  timeout: 1000
  
  
