server:
  port: 0
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin4321
    driver-class-name: com.mysql.jdbc.Driver
    #initialization-mode: always
    jpa:
      hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      properties:
      show_sql: true
      format_sql: true
 
      
  logging:
    level:
      org:
        hibernate:
          type: trace

